### PR TITLE
Add provided scope to lombok, otherwise no dependents

### PR DESCRIPTION
**Pull request by ProfElements**
I can't do proper gastro integration without this one change (quite litterally cant compile)

### CODE REVIEW

**Comment by SchnTgaiSpock** [comment]
wdym can't compile? you should be able to do smth like
```

        <dependency>
            <groupId>com.github.SchnTgaiSpock</groupId>
            <artifactId>Gastronomicon</artifactId>
            <version>v1.0.0</version>
            <scope>provided</scope>
        </dependency>
```

**Comment by ProfElements** [comment]
better stacktrace 
image

**Comment by SchnTgaiSpock** [comment]
ok i will check in a bit, i don't think provided scope for lombok is the way to go though, since that means the jar has to be in the server plugins dir

**Comment by ProfElements** [comment]
Its the only difference between InfinityXpansion which also used lombok and your plugin

**Comment by SchnTgaiSpock** [comment]
hmm ok then

**Comment by SchnTgaiSpock** [comment]
1.1.0 version on jitpack should be up soon

**Pull request merged**
